version: "3"
services:
  manager:
    command: sh start.sh
    build: .
    image: instagramtools/manager
    ports:
      - 5000:5000
    volumes:
      - ./src:/app
    depends_on:
      - postgres
    links:
      - postgres:postgres
    environment:
      - DEBUG=True
      - SECRET_KEY=5(15ds+i2+%ik6z&!yer+ga9m=e%jcqiz_5wszg)r-z!2--b2d
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_SERVICE=postgres
      - DB_PORT=5432
      - PATH_TO_SSH_KEY=tk
      - IP=tk
  postgres:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres

  web:
    image: instagramtools/web
    environment:
    - PYTHONUNBUFFERED=0
    depends_on:
    - selenium
    volumes:
    - ./logs:/code/logs
  selenium:
    image: selenium/standalone-chrome
    ports:
    - 5900:5900

volumes:
  db_data:
  log_data: