version: "3"
services:
  manager:
    command: python start.py
    restart: unless-stopped
    build: .
    image: instagramtools/manager
    volumes:
      - ./src:/app
    ports:
      - 8765:8765
    depends_on:
      - postgres
    links:
      - postgres:postgres
    environment:
      - DEBUG=True
      - P_USER=docker
      - SECRET_KEY=5(15ds+i2+%ik6z&!yer+ga9m=e%jcqiz_5wszg)r-z!2--b2d
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_SERVICE=postgres
      - DB_PORT=5432
#    env_file:
#      - .env/.bot-manager.env

  nginx:
    image: instagramtools/user-interface
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DEBUG=off
      - APP_API_PLACEHOLDER=/api
      - APP_API_GATEWAY=http://api:8000
      - APP_BOT_PLACEHOLDER=/bot
      - APP_BOT_GATEWAY=http://manager:8765
      - PAYMENT_PLACEHOLDER=/pay
      - PAYMENT_GATEWAY=http://payment-manager:7000
    depends_on:
      - api
      - payment-manager
      - manager
    links:
      - api:api
      - payment-manager:payment-manager
      - manager:manager
  api:
    image: instagramtools/api
    depends_on:
      - postgres
      - manager
    links:
      - postgres:postgres
      - manager:manager
    environment:
      - DEBUG=False
      - DB_SERVICE=postgres
      - DB_PORT=5432
      - APP_BOT_GATEWAY=http://manager:8765
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - SECRET_KEY=SECRET_KEY
      - SECURITY_PASSWORD_SALT=SECURITY_PASSWORD_SALT
    env_file:
      - .env/.mail.env
  payment-manager:
    image: instagramtools/payment-manager
    depends_on:
      - postgres
      - api
    links:
      - postgres:postgres
      - api:api
    ports:
      - "7000:7000"
    environment:
      - DEBUG=False
      - DB_SERVICE=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - STRIPE_SECRET_KEY=TEST

  postgres:
    image: postgres:latest
    volumes:
      - pgs_data:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres

  web:
    image: instagramtools/web
    environment:
    - PYTHONUNBUFFERED=0
    depends_on:
    - selenium
    volumes:
    - ./logs:/code/logs
  selenium:
    image: selenium/standalone-chrome
    ports:
    - 5900:5900

volumes:
  pgs_data:
  log_data: